### ISSUE TITLE
@sorrir/bluetooth is now blauzahn

### ISSUE THREAD

**Issue by QuadratClown** [jhanssen/halo-mqtt#1]
Hello!

I'm the developer of @sorrir/bluetooth. I saw that you were using my package and wanted to give a heads up that it will no longer be maintained. Future development will continue as [blauzahn](https://www.npmjs.com/package/blauzahn). If any issues occur during migration, please hit me up.

**Comment by jhanssen** [comment]
Thanks for the update, will update my package.json. And thanks for the project as well, works well.
